### ISSUE TITLE
Meta: enable input groups

### ISSUE THREAD

**Issue by mtojek** [elastic/package-spec#144]
Follow-up on https://github.com/elastic/package-spec/issues/132

We've an agreement on the structure proposal in https://github.com/elastic/package-spec/pull/137 , so here is the list of next action items:
- [x] elastic-package: update the package-spec with changes in https://github.com/elastic/package-spec/pull/137 and point no. 1 (integrity between data streams) - https://github.com/elastic/elastic-package/pull/267
- [x] package-spec: enforce referential integrity between `data_streams` mentioned in policy template items and folders under `<package root>/data_stream/` - https://github.com/elastic/package-spec/pull/143
- [x] integrations: update elastic-package - https://github.com/elastic/integrations/pull/754
- [x] elastic-package: build multiple README files - https://github.com/elastic/elastic-package/pull/282
- [ ] integrations: modify the AWS package to use input groups (merge only if Kibana and Package Registry support it) https://github.com/elastic/integrations/pull/767
- [x] package-registry: support input groups, check with the modified AWS package https://github.com/elastic/package-registry/pull/685
- [x] kibana: support input groups https://github.com/elastic/kibana/issues/93315
- [ ] package-storage: release the package

**Comment by jen-huang** [comment]
@mtojek Just want to clarify, the package registry work includes:
- Returning the new package fields
- Adjusting `/search` endpoint to return results based on `policy_templates` items

Does that look right?

**Comment by mtojek** [comment]
Yes Jen, precisely.

**Comment by jen-huang** [comment]
Kibana support is merged!
* https://github.com/elastic/kibana/pull/99866
* https://github.com/elastic/kibana/pull/101531

**Comment by mtojek** [comment]
I think we can close this "meta", the only leftover is https://github.com/elastic/integrations/pull/767 . Kubernetes has just been merged. Thank you for all your work!
