### ISSUE TITLE
Checklist for version 2.0.0

### ISSUE THREAD

**Issue by jsoriano** [elastic/package-spec#399]
List of pending changes that we want to have in 2.0.0 before releasing it:
- [x] https://github.com/elastic/elastic-package/issues/615
  - [x] https://github.com/elastic/elastic-package/pull/765
- [x] https://github.com/elastic/elastic-package/issues/837
  - [x] https://github.com/elastic/elastic-package/pull/961
- [x] https://github.com/elastic/package-spec/issues/217
  - [x] https://github.com/elastic/elastic-package/pull/968
- [x] https://github.com/elastic/package-spec/issues/408
  - [x] https://github.com/elastic/package-spec/pull/412
- [x] https://github.com/elastic/package-spec/issues/92
- [x] https://github.com/elastic/package-spec/issues/282
  - [x] https://github.com/elastic/package-spec/pull/420

Postponed
- [ ] https://github.com/elastic/elastic-package/issues/147
       It should be built upon https://github.com/elastic/package-spec/issues/199, and it won't be so breaking in that case.
- [ ] https://github.com/elastic/package-spec/issues/57
       There are also checks in Kibana, if some package is broken now it cannot be used. We can add validations here in a next version.

Related:
- [x] https://github.com/elastic/elastic-package/issues/963
  - [x] https://github.com/elastic/elastic-package/pull/964 
  - [x] https://github.com/elastic/elastic-package/pull/974

**Comment by jsoriano** [comment]
Checklist completed and version 2 announced, closing this.
