### ISSUE TITLE
[META] Semantic validations

### ISSUE THREAD

**Issue by ycombinator** [elastic/package-spec#47]
The package spec allows for syntactic validations of packages. These validate the _structure_ of package contents. They have been implemented via https://github.com/elastic/package-spec/pull/14, https://github.com/elastic/package-spec/pull/41, and several minor follow up PRs.

There is also a need for semantic validations. These validate that values found in package contents conform to further rules that may not be expressible in the spec itself. For example:

* [x] Validate that icon and screenshot sources exist: https://github.com/elastic/package-spec/issues/31
* [ ] Validate that dashboard IDs start with package names: https://github.com/elastic/package-spec/issues/65
* [ ] Ensure consistency between CHANGELOG and manifest: https://github.com/elastic/package-spec/issues/167

**Comment by ruflin** [comment]
* Validation for ingest pipelines: https://github.com/elastic/package-registry/blob/master/util/dataset.go#L168

**Comment by ycombinator** [comment]
Hey @ruflin, I'm starting to look into this issue now. Could you elaborate on your comment (https://github.com/elastic/package-spec/issues/47#issuecomment-694693842) please? The link in the comment is now dead so I can't figure out what you meant. Thanks!

**Comment by ruflin** [comment]
If I remember correctly this was about validating that a pipeline name that was used in the manifest actually exists. Basically any file that can be referenced from the manifest file like icons, readmes, pipelines, etc. should be validated that it exists.

**Comment by mtojek** [comment]
@ycombinator Would you mind updating the status of this issue? You have made a significant progress here recently.

**Comment by ycombinator** [comment]
There is no direct update to this issue because of the recent progress. However, I updated https://github.com/elastic/package-spec/issues/65 which is linked from this issue.

Separately, I also added https://github.com/elastic/package-spec/issues/167 to the checklist on this issue.

**Comment by jsoriano** [comment]
Checklist was completed, closing this. Please open new issues for additional validations.
