### ISSUE TITLE
Package Spec v3

### ISSUE THREAD

**Issue by jsoriano** [elastic/package-spec#539]
We are starting to discuss about some potentially breaking changes that we would like to include, let's start to list them to prepare a new major. 

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/elastic-package/issues/1435
- [ ] https://github.com/elastic/package-spec/issues/538
- [x] Validation of dangling kibana objects https://github.com/elastic/package-spec/blob/450bd34f8bf3bb1274dd01a0c2ff4d33ad4e90d0/code/go/internal/validator/semantic/validate_kibana_no_dangling_object_ids.go#L15 https://github.com/elastic/package-spec/pull/589
- [ ] https://github.com/elastic/package-spec/issues/559
- [x] Try to fix consistent rendering of empty groups in docs, see https://github.com/elastic/elastic-package/pull/1335#discussion_r1248039405
- [ ] https://github.com/elastic/package-spec/issues/317
- [ ] https://github.com/elastic/package-spec/issues/596
- [ ] https://github.com/elastic/ingest-dev/issues/2174
- [ ] https://github.com/elastic/elastic-package/pull/1464
- [x] Remove ValidationErrors from public validator package https://github.com/elastic/package-spec/pull/625
- [ ] https://github.com/elastic/elastic-package/issues/1470
- [ ] https://github.com/elastic/package-spec/issues/624
- [ ] https://github.com/elastic/package-spec/pull/629
- [ ] https://github.com/elastic/package-spec/pull/626
- [ ] https://github.com/elastic/package-spec/pull/635
- [ ] https://github.com/elastic/package-spec/pull/636
- [ ] https://github.com/elastic/package-spec/pull/613
```

**Comment by jsoriano** [comment]
test integrations

**Comment by jlind23** [comment]
@jsoriano now that https://github.com/elastic/elastic-package/issues/1470 is on its way, what else would be missing here to consider this as done?

**Comment by jsoriano** [comment]
@jlind23 we have a couple of small last-minute PRs, and we have to do the actual release.
